version: "3"

services:
  db:
    image: postgres:14.5-alpine
    container_name: proto-DB
    environment:
      POSTGRES_DB: proto
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./database/start:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/postgresql/data
    ports:
      - 5555:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d proto"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  backend:
    build: ./back
    container_name: proto-back
    ports:
      - 7000:7000
    depends_on:
      - db

  frontend:
    build: ./front
    container_name: proto-front
    ports:
      - 80:80
    depends_on:
      - backend
